version: '3.8'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'zavocado'
    environment:
      - POSTGRES_USER=sabine
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=zavocado
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped